document.writeln("<!DOCTYPE html>");
document.writeln("<!--[if lt IE 7]>      <html class=\'no-js lt-ie9 lt-ie8 lt-ie7\'> <![endif]-->");
document.writeln("<!--[if IE 7]>         <html class=\'no-js lt-ie9 lt-ie8\'> <![endif]-->");
document.writeln("<!--[if IE 8]>         <html class=\'no-js lt-ie9\'> <![endif]-->");
document.writeln("<!--[if gt IE 8]><!--> <html class=\'no-js\'> <!--<![endif]-->");
document.writeln("    <head>");
document.writeln("        <meta charset=\'utf-8\'>");
document.writeln("        <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("        <title></title>");
document.writeln("        <meta name=\'description\' content=\'\'>");
document.writeln("        <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("        <link rel=\'stylesheet\' href=\'\'>");
document.writeln("    </head>");
document.writeln("    <body>");
document.writeln("        <!--[if lt IE 7]>");
document.writeln("            <p class=\'browsehappy\'>You are using an <strong>outdated</strong> browser. Please <a href=\'#\'>upgrade your browser</a> to improve your experience.</p>");
document.writeln("        <![endif]-->");
document.writeln("        <div class=\'footer\'>");
document.writeln("                <div class=\'footer-nav\'>");
document.writeln("                    <ul>");
document.writeln("                        <li>首页</li>");
document.writeln("                        <li>关于安孚</li>");
document.writeln("                        <li>服务领域</li>");
document.writeln("                        <li>安孚团队</li>");
document.writeln("                        <li>安孚业绩</li>");
document.writeln("                        <li>人才招聘</li>");
document.writeln("                        <li>联系我们</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'footer-qrCode\'>");
document.writeln("                    <div class=\'left\'>");
document.writeln("                        <img src=\'./images/qrCord.jpg\' width=\'100px\'>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'right\'>");
document.writeln("                        <div>安 | 如 | 泰 | 山</div>");
document.writeln("                        <div>深 | 孚 | 众 | 望</div>");
document.writeln("                        <div>扫一扫关注我们</div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'copyright\'>");
document.writeln("                    Copyright © 2017 ANFU LAW OFFICES 版权所有 苏州市安孚律师事务所");
document.writeln("                </div>");
document.writeln("                <div class=\'copyright\'>");
document.writeln("                    苏ICP备09032311号");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        <script src=\'\' async defer></script>");
document.writeln("    </body>");
document.writeln("</html>");