document.writeln("<!DOCTYPE html>");
document.writeln("<!--[if lt IE 7]>      <html class=\'no-js lt-ie9 lt-ie8 lt-ie7\'> <![endif]-->");
document.writeln("<!--[if IE 7]>         <html class=\'no-js lt-ie9 lt-ie8\'> <![endif]-->");
document.writeln("<!--[if IE 8]>         <html class=\'no-js lt-ie9\'> <![endif]-->");
document.writeln("<!--[if gt IE 8]><!--> <html class=\'no-js\'> <!--<![endif]-->");
document.writeln("    <head>");
document.writeln("        <meta charset=\'utf-8\'>");
document.writeln("        <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("        <title></title>");
document.writeln("        <meta name=\'description\' content=\'\'>");
document.writeln("        <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("        <link rel=\'stylesheet\' href=\'\'>");
document.writeln("    </head>");
document.writeln("    <body>");
document.writeln("        <!--[if lt IE 7]>");
document.writeln("            <p class=\'browsehappy\'>You are using an <strong>outdated</strong> browser. Please <a href=\'#\'>upgrade your browser</a> to improve your experience.</p>");
document.writeln("        <![endif]-->");
document.writeln("        <div class=\'header size\'>");
document.writeln("                <div class=\'logo\'>");
document.writeln("                    <img src=\'./images/logo.png\'>");
document.writeln("                </div>");
document.writeln("                <div class=\'nav\'>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'./index.html\'>首页</a></li>");
document.writeln("                        <li><a href=\'./about.html\'>关于安孚</a></li>");
document.writeln("                        <li><a href=\'./server.html\'>服务领域</a></li>");
document.writeln("                        <li><a href=\'./team.html\'>安孚团队</a></li>");
document.writeln("                        <li><a href=\'./achievement.html\'>安孚业绩</a></li>");
document.writeln("                        <li><a href=\'./recruit.html\'>人才招聘</a></li>");
document.writeln("                        <li><a href=\'./contact.html\'>联系我们</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        <script src=\'\' async defer></script>");
document.writeln("    </body>");
document.writeln("</html>");